export  const posts = [
    {
      id: '1',
      title: 'Complete Guide to Next.js 14',
      summary: 'In this article, youll get familiar with the latest version of Next.js, version 14. We’ll walk through the new features like the App Router, Server Actions, the updated folder structure, performance optimizations, and developer experience improvements. If youre looking to build modern, scalable apps, this guide is a perfect starting point.',
      slug: 'nextjs-14-guide',
      image: 'https://picsum.photos/seed/nextjs/800/500',
      author: 'Mohammad Rezaei',
      date: '2024-11-20',
    },
    
    {
      id: '2',
      title: 'How Does React Query Work?',
      summary: 'This post dives deep into React Query and how it manages data fetching, caching, error handling, and automatic updates. Especially useful in large React and Next.js projects, React Query simplifies data management and improves overall app performance.',
      slug: 'how-react-query-works',
      image: 'https://picsum.photos/seed/reactquery/800/500',
      author: 'Sara Kazemi',
      date: '2024-10-14',
    },
    {
      id: '3',
      title: 'Build a Blog with Next.js',
      summary: 'Looking to build a complete blog using Next.js? This post guides you through choosing the right CMS or building your own API, designing the UI, and making everything responsive. You’ll learn how to create a blog that’s scalable, clean, and professional.',
      slug: 'build-blog-with-nextjs',
      image: 'https://picsum.photos/seed/blog/800/500',
      author: 'Ahmad Jalili',
      date: '2024-09-01',
    },
    {
      id: '4',
      title: 'Why Use the App Router?',
      summary: 'The App Router is one of the biggest structural changes in Next.js. In this article, we explore the benefits of using the App Router over the traditional Pages Router, and how it improves both the developer experience and the performance of your application.',
      slug: 'why-app-router',
      image: 'https://picsum.photos/seed/router/800/500',
      author: 'Leila Ghaderi',
      date: '2024-08-25',
    },
    {
      id: '5',
      title: 'Server Actions vs API Routes',
      summary: 'Next.js 14 introduces Server Actions, a new way to handle server-side logic. In this post, you’ll learn when to use Server Actions and when to stick with traditional API routes. We break down the pros, cons, and best use cases of each.',
      slug: 'server-actions-vs-api',
      image: 'https://picsum.photos/seed/serveractions/800/500',
      author: 'Nima Karimi',
      date: '2024-07-12',
    },
    {
      id: '6',
      title: 'Responsive UI with Tailwind',
      summary: 'Tailwind CSS is one of the most powerful tools for building responsive interfaces. This article teaches you how to use Tailwind’s responsive utility classes to create flexible UIs that work perfectly across all screen sizes — without writing custom media queries.',
      slug: 'responsive-ui-with-tailwind',
      image: 'https://picsum.photos/seed/tailwind/800/500',
      author: 'Maryam Nasiri',
      date: '2024-06-05',
    },
    {
      id: '7',
      title: 'Getting Started with TypeScript in Next.js',
      summary: 'Adding TypeScript to your Next.js project brings structure, safety, and scalability. This guide is perfect for beginners, covering setup, type definitions, props handling, and how to use TypeScript effectively in components and pages.',
      slug: 'typescript-in-nextjs',
      image: 'https://picsum.photos/seed/typescript/800/500',
      author: 'Amir Heydari',
      date: '2024-05-10',
    },
    {
      id: '8',
      title: 'Building a Contact Form in Next.js',
      summary: 'Every website needs a contact form. In this post, we’ll show you how to build a functional and clean contact form using Next.js — from managing input with controlled components to integrating an email-sending service.',
      slug: 'contact-form-nextjs',
      image: 'https://picsum.photos/seed/contact/800/500',
      author: 'Zahra Moradi',
      date: '2024-04-02',
    },
    {
      id: '9',
      title: 'Understanding SSR in Next.js',
      summary: 'Server Side Rendering (SSR) is a powerful rendering method that boosts performance and SEO. This article explains the differences between SSR, SSG, and CSR, and when and how to implement SSR in your Next.js applications.',
      slug: 'ssr-in-nextjs',
      image: 'https://picsum.photos/seed/ssr/800/500',
      author: 'Keyvan Ahmadi',
      date: '2024-03-18',
    },
    {
      id: '10',
      title: 'Fetching Data with SWR',
      summary: 'SWR is a lightweight data-fetching library by Vercel. In this article, we cover how to use SWR in your React or Next.js apps, cache responses, handle loading and error states, and improve your overall data fetching strategy.',
      slug: 'data-fetching-with-swr',
      image: 'https://picsum.photos/seed/swr/800/500',
      author: 'Shayan Hosseini',
      date: '2024-02-06',
    },
  ]