'use client'
import type { Metadata } from "next";
import "./styles/globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";




// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient()
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <QueryClientProvider  client={queryClient}>
        {children}
        </QueryClientProvider>
      </body>
    </html>
  );
}
